<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.php">Lenguajes de Programación</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
            </button>
        </div>
                        
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="java.php">
                        <img src="https://ideapps.com.co/wp-content/uploads/2016/10/java-logo.png" height="40px" width="60px">
                    </a>
                </li>
                <li>
                    <a href="javascript.php">
                        <img src="https://i0.wp.com/www.lanaranjabionica.com/wp-content/uploads/2016/03/js-logo.png?fit=500%2C500&ssl=1" height="40px" width="60px">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>